In [48]:
import pandas as pd

In [49]:
cat_data = pd.read_csv('./data/cat_data.csv')
cat_data

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
0,34.0,Female,86.7,1.86,174,152.0,74.0,1.12,712.0,Strength,12.8,2.4,5.0,2.0,14.31
1,26.0,Female,84.7,1.83,166,156.0,73.0,1.00,833.0,Strength,27.9,2.8,5.0,2.0,33.49
2,22.0,Male,64.8,1.85,187,166.0,64.0,1.24,1678.0,Cardio,28.7,1.9,3.0,2.0,12.73
3,54.0,Female,75.3,1.82,187,169.0,58.0,1.45,628.0,Cardio,31.8,2.4,4.0,1.0,20.37
4,34.0,Female,52.8,1.74,177,169.0,66.0,1.60,1286.0,Strength,26.4,3.2,4.0,2.0,20.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,54.0,Male,88.5,2.00,173,134.0,58.0,1.11,1388.0,HIIT,27.7,3.7,3.0,2.0,36.73
1796,52.0,Male,84.3,1.69,164,169.0,54.0,0.77,1367.0,HIIT,32.6,2.9,3.0,2.0,15.11
1797,47.0,Male,70.1,1.84,188,129.0,67.0,1.20,1261.0,Strength,28.4,2.5,3.0,2.0,17.99
1798,35.0,Male,49.3,1.71,180,152.0,73.0,1.04,956.0,Cardio,32.9,1.7,4.0,3.0,12.65
1799,40.0,Male,79.5,1.92,184,156.0,52.0,1.29,1178.0,Strength,14.7,1.5,4.0,1.0,23.51

In [50]:
#cat_data.info()

numerical_cols = cat_data.select_dtypes(include=['float64']).columns.tolist()
numerical_cols

['Age',
 'Weight (kg)',
 'Height (m)',
 'Avg_BPM',
 'Resting_BPM',
 'Session_Duration (hours)',
 'Calories_Burned',
 'Fat_Percentage',
 'Water_Intake (liters)',
 'Workout_Frequency (days/week)',
 'Experience_Level',
 'BMI']

In [51]:
categorical_cols = cat_data.select_dtypes(include=['object']).columns.tolist()
categorical_cols

['Gender', 'Max_BPM', 'Workout_Type']

In [52]:
cat_data.describe()

,Age,Weight (kg),Height (m),Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
count,1790.000000,1778.000000,1774.000000,1770.000000,1781.000000,1777.000000,1777.000000,1784.000000,1776.000000,1742.000000,1743.000000,1770.000000
mean,34.475419,67.606637,1.739233,146.259322,63.951151,1.391598,1033.698931,23.509361,2.706644,3.339265,1.823867,19.957774
std,12.315728,19.861408,0.123892,15.219516,7.936502,0.372342,328.049662,5.865557,0.710224,0.947955,0.746568,6.573175
min,18.000000,40.000000,1.500000,120.000000,50.000000,0.500000,303.000000,10.000000,1.500000,2.000000,1.000000,12.320000
25%,23.000000,52.300000,1.650000,133.250000,57.000000,1.130000,794.000000,20.500000,2.100000,3.000000,1.000000,14.780000
50%,33.000000,65.300000,1.730000,146.000000,65.000000,1.370000,1030.000000,24.300000,2.800000,3.000000,2.000000,18.690000
75%,45.000000,80.100000,1.820000,160.000000,72.000000,1.640000,1249.000000,27.500000,3.400000,4.000000,2.000000,23.517500
max,59.000000,129.900000,2.000000,169.000000,74.000000,2.000000,1783.000000,35.000000,3.700000,5.000000,3.000000,49.840000

In [53]:
cat_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            1790 non-null   float64
 1   Gender                         1729 non-null   object
 2   Weight (kg)                    1778 non-null   float64
 3   Height (m)                     1774 non-null   float64
 4   Max_BPM                        1779 non-null   object
 5   Avg_BPM                        1770 non-null   float64
 6   Resting_BPM                    1781 non-null   float64
 7   Session_Duration (hours)       1777 non-null   float64
 8   Calories_Burned                1777 non-null   float64
 9   Workout_Type                   1739 non-null   object
 10  Fat_Percentage                 1784 non-null   float64
 11  Water_Intake (liters)          1776 non-null   float64
 12  Workout_Frequency (days/week)  1742 non-null   float64
 13  Experience_Level               1743 non-null   float64
 14  BMI                            1770 non-null   float64
dtypes: float64(12), object(3)
memory usage: 211.1+ KB

In [54]:
cat_data[['Age', 'Gender', 'Workout_Type', 'Calories_Burned', 'BMI']]

       Age  Gender Workout_Type  Calories_Burned    BMI
0     34.0  Female     Strength            712.0  14.31
1     26.0  Female     Strength            833.0  33.49
2     22.0    Male       Cardio           1678.0  12.73
3     54.0  Female       Cardio            628.0  20.37
4     34.0  Female     Strength           1286.0  20.83
...    ...     ...          ...              ...    ...
1795  54.0    Male         HIIT           1388.0  36.73
1796  52.0    Male         HIIT           1367.0  15.11
1797  47.0    Male     Strength           1261.0  17.99
1798  35.0    Male       Cardio            956.0  12.65
1799  40.0    Male     Strength           1178.0  23.51

[1800 rows x 5 columns]

In [60]:
cat_data.loc[cat_data['Workout_Type'] == 'Cardio']

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
2,22.0,Male,64.8,1.85,187,166.0,64.0,1.24,1678.0,Cardio,28.7,1.9,3.0,2.0,12.73
3,54.0,Female,75.3,1.82,187,169.0,58.0,1.45,628.0,Cardio,31.8,2.4,4.0,1.0,20.37
6,44.0,Female,46.5,1.81,191,142.0,74.0,1.46,1238.0,Cardio,11.9,3.7,2.0,2.0,18.12
14,19.0,Female,71.7,1.91,197,148.0,74.0,1.15,464.0,Cardio,32.5,2.7,4.0,2.0,19.09
17,39.0,Female,71.3,1.77,171,124.0,74.0,0.69,871.0,Cardio,21.9,2.1,5.0,1.0,14.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1777,18.0,Male,62.7,1.87,184,141.0,59.0,1.59,708.0,Cardio,10.3,1.5,2.0,2.0,13.14
1784,51.0,Male,80.8,2.00,167,129.0,55.0,1.52,1454.0,Cardio,33.9,1.6,3.0,1.0,12.58
1786,18.0,Male,42.3,1.64,198,169.0,65.0,1.55,1199.0,Cardio,26.4,3.2,4.0,1.0,15.26
1793,20.0,Male,40.0,1.81,176,138.0,66.0,1.44,1210.0,Cardio,23.0,3.6,4.0,2.0,12.32
1798,35.0,Male,49.3,1.71,180,152.0,73.0,1.04,956.0,Cardio,32.9,1.7,4.0,3.0,12.65

In [56]:
def get_unique_workouts():
   unique_workouts = (cat_data['Workout_Type']
                     .dropna()
                     .str.strip()
                     .str.title()
                     .unique())

   for workout in sorted(unique_workouts):
       print(f"  - {workout}")

   return unique_workouts
unique_workouts = get_unique_workouts()

  - Cardio
  - Hiit
  - Strength
  - Yoga
  - \Nstrength
  - \Tcardio
  - \Tyoga

In [57]:
cat_data.columns

Index(['Age', 'Gender', 'Weight (kg)', 'Height (m)', 'Max_BPM', 'Avg_BPM',
       'Resting_BPM', 'Session_Duration (hours)', 'Calories_Burned',
       'Workout_Type', 'Fat_Percentage', 'Water_Intake (liters)',
       'Workout_Frequency (days/week)', 'Experience_Level', 'BMI'],
      dtype='object')

In [58]:
new_df = cat_data.loc[(cat_data['Gender'] == 'Female') & (cat_data['BMI'] > 25) & (cat_data['Workout_Frequency (days/week)'] > 3)]

new_df

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
1,26.0,Female,84.7,1.83,166,156.0,73.0,1.00,833.0,Strength,27.9,2.8,5.0,2.0,33.49
32,44.0,Female,45.0,1.53,199,158.0,50.0,0.70,930.0,Strength,21.9,3.6,4.0,1.0,27.74
54,36.0,Female,40.0,1.71,178,169.0,69.0,1.30,1519.0,HIIT,27.5,2.7,4.0,1.0,39.74
66,33.0,Female,76.3,1.95,188,125.0,72.0,0.95,899.0,Strength,21.7,2.3,5.0,1.0,26.08
100,30.0,Female,96.3,2.00,173,136.0,74.0,2.00,1095.0,HIIT,20.4,1.5,5.0,2.0,25.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1700,58.0,Female,73.3,1.69,180,156.0,72.0,1.60,1350.0,Yoga,25.4,3.0,4.0,1.0,38.45
1717,33.0,Female,99.6,1.72,164,169.0,70.0,1.41,962.0,HIIT,23.6,3.7,5.0,2.0,28.70
1731,20.0,Female,86.0,1.69,183,136.0,58.0,1.16,861.0,Strength,23.3,3.6,5.0,NaN,28.85
1752,49.0,Female,59.2,1.55,185,169.0,63.0,1.32,1169.0,Yoga,25.1,1.7,4.0,1.0,27.18
1755,18.0,Female,68.1,1.66,160,120.0,65.0,1.43,1343.0,Cardio,27.2,3.3,4.0,1.0,25.77

In [59]:
criteria = cat_data.loc[(cat_data['BMI'] > 30) & (cat_data['Fat_Percentage'] > 25)]

len(criteria)

60